version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: pg-pricenest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_pricenest
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-pricenest
    ports:
      - "6379:6379"

volumes:
  postgres-data:
